project:
  type: book

book:
  title: "Thesis title"
  author: "Student Name"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

bibliography: references.bib
csl: apa.csl

degreetype: Bachelor of Science
submission_date: 2026-09-01
stud_id: 12345678
advisor: "Prof. Dr. Gerit Wagner"
affiliation: Management Department

format:
  monashthesis-html: default
  monashthesis-pdf: default
